export default {
  products: [
    {
      id: 1,
      user_id: 1,
      date_added: 'September 5, 2020',
      name: 'Samsung Refridgerator',
      url: 'https://www.bestbuy.com/site/samsung-28-cu-ft-large-capacity-3-door-french-door-refrigerator-with-autofill-water-pitcher-fingerprint-resistant-stainless-steel/6417768.p?skuId=6417768',
      comments: 'Has tons of storage!',
      category: 'Kitchen',
    },
    {
      id: 2,
      user_id: 1,
      date_added: 'September 10, 2020',
      name: 'Sonos TV Soundbar',
      url: 'https://www.bestbuy.com/site/sonos-beam-soundbar-with-voice-control-built-in-black/6253409.p?skuId=6253409',
      comments: 'Great sound!',
      category: 'Living Room',
    },
    {
      id: 3,
      user_id: 2,
      date_added: 'October 5, 2020',
      name: 'Sienna High Table & 4 Barstools',
      url: 'https://www.cityfurniture.com/product/9715395/ei-sienna-dark-tone-high-tbl-4-bs-9715395',
      comments: 'We have the dark tone color.',
      category: 'Dining Room',
    },
    {
      id: 4,
      user_id: 2,
      date_added: 'October 10, 2020',
      name: 'Raegan Gray Fabric Right Chaise Sectional',
      url: 'https://www.cityfurniture.com/product/9711891/gy-raegan-gray-fabric-right-chaise-sect',
      comments: 'Such a comfy couch!',
      category: 'Living Room',
    },
    {
      id: 5,
      user_id: 3,
      date_added: 'November 5, 2020',
      name: 'Lacey Gray Uph Platform Bed',
      url: 'https://www.cityfurniture.com/product/9716528/lacey-gray-uph-platform-bed',
      comments: '',
      category: 'Bedroom',
    },
    {
      id: 6,
      user_id: 3,
      date_added: 'November 10, 2020',
      name: 'Sutton Light Tone Dresser',
      url: 'https://www.cityfurniture.com/product/35006/sg-sutton-dark-tone-dresser',
      comments: 'Great quality dresser.',
      category: 'Kitchen',
    },
  ],
  groups: [
    {
      id: 1,
      name: 'Group ABC',
      code: 'apples',
    },
    {
      id: 2,
      name: 'Group XYZ',
      code: 'bananas',
    },
  ]
}